
---
apiVersion: v1
kind: Service
metadata:
  name: ben-app-frontend-service
  namespace: ben-app
spec:
  selector:
    app: ben-app-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer



