---
apiVersion: v1
kind: Service
metadata:
  name: ben-app-backend-service
  namespace: ben-app
spec:
  selector:
    app: ben-app-backend
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: LoadBalancer


