---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: pod-creator
  namespace: ben-app
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - create

---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: pod-creator-sa
  namespace: ben-app

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: pod-creator-binding
  namespace: ben-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-creator
subjects:
- kind: ServiceAccount
  name: pod-creator-sa
  namespace: ben-app

