apiVersion: v1
kind: Pod
metadata:
  annotations:
  labels:
    app: app-alpine
    env: dev
  name: app-alpine
  namespace: ben-app
spec:
  containers:

  - name: app-alpine
    image: alpine
    command: ["/bin/sh", "-c"]
    args: 
      - echo "This is my message to the world"; 
        sleep 15;
  restartPolicy: Never
